#!/bin/bash

version="v1.0"

function help {
  echo "Usage:"
  echo "'${0##*/} [sudo] COMMAND'"
  echo "starts a program or executes a comand without any output"
  echo
  echo "'${0##*/} --update'"
  echo "checks for updates and installs them if necessary"
  echo
  echo "'${0##*/} --uninstall'"
  echo "uninstalls ${0##*/} command"
  echo
  echo "$version"
  echo "programmed by Christoph Stögmüller"
  echo "https://github.com/cstogmuller/run-linux-command-without-output"
}

if [ -z ${1+x} ] || [ "$1" == "--help" ]; then
  help
else
  if [ $1 == "--uninstall" ]; then
    read -e -p "This will remove the ${0##*/} command. Are you sure? [Y/n] " uninstall
    if [ "$uninstall" == "y" ] || [ "$uninstall" == "Y" ]; then
      sudo rm -f -v ${0}
      echo "Uninstall complete."
    else
      echo "Abort."
    fi
  else
    if [ $1 == "--update" ]; then
      echo "Checking for updates..."
      if ping -q -w 1 -c 1 github.com > /dev/null 2>&1; then
        wget -t 0 -O "/tmp/version" https://raw.githubusercontent.com/cstogmuller/run-linux-command-without-output/main/version 2>&1 | grep -i "failed\|error"
        if [ `cat /tmp/version` == "$version" ]; then
          rm /tmp/version
          echo "You have the latest version."
        else
          rm /tmp/version
          echo "A newer version is available."
          cd ~/
          rm -d -r -f ~/run-linux-command-without-output > /dev/null
          git clone https://github.com/cstogmuller/run-linux-command-without-output.git
          cd
          chmod a+x ~/run-linux-command-without-output/install-run.sh
          source ~/run-linux-command-without-output/update
        fi
      else
        echo "You are offline!"
      fi
    else
      if [[ "${@}" == "sudo "* ]] || [[ "${@}" == *" sudo "* ]]; then
        echo "Applying root privileges..."
        sudo echo "${@} > /dev/null 2>&1 &" | /bin/bash
      else
        echo "${@} > /dev/null 2>&1 &" | /bin/bash
      fi
    fi
  fi
fi
